"""Initial migration

Revision ID: 80a9d69c4dd3
Revises: 
Create Date: 2025-07-18 14:46:25.269435

"""
from alembic import op
from alembic.util.sqla_compat import _server_default_is_computed
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80a9d69c4dd3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consultation_type', sa.String(length=50), nullable=False,server_default='video'))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=False,server_default='0000000000'))
        batch_op.add_column(sa.Column('emergency_contact', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('notification_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('psychologist_notified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('psychologist_notified')
        batch_op.drop_column('notification_sent')
        batch_op.drop_column('emergency_contact')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('consultation_type')

    # ### end Alembic commands ###
